import { Settings } from 'luxon';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import '@/styles/globals.css';
import { Footer } from '@/components/footer';
import { Header } from '@/components/header';

Settings.defaultZone = 'Asia/Tokyo';
Settings.defaultLocale = 'ja-JP';

if (process.env.NEXT_RUNTIME === 'nodejs' && process.env.NODE_ENV === 'development') {
  const { server } = await import('@/mocks/server');
  server.listen();
}

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className='min-h-screen flex flex-col p-4 bg-background items-center'>
          <Header />

          <main className='flex-1 w-full max-w-7xl'>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
