- weather_code: 100
  name: 晴
- weather_code: 101
  name: 晴時々曇
- weather_code: 102
  name: 晴一時雨
- weather_code: 103
  name: 晴時々雨
- weather_code: 104
  name: 晴一時雪
- weather_code: 105
  name: 晴時々雪
- weather_code: 106
  name: 晴一時雨か雪
- weather_code: 107
  name: 晴時々雨か雪
- weather_code: 108
  name: 晴一時雨か雷雨
- weather_code: 110
  name: 晴後時々曇
- weather_code: 111
  name: 晴後曇
- weather_code: 112
  name: 晴後一時雨
- weather_code: 113
  name: 晴後時々雨
- weather_code: 114
  name: 晴後雨
- weather_code: 115
  name: 晴後一時雪
- weather_code: 116
  name: 晴後時々雪
- weather_code: 117
  name: 晴後雪
- weather_code: 118
  name: 晴後雨か雪
- weather_code: 119
  name: 晴後雨か雷雨
- weather_code: 120
  name: 晴朝夕一時雨
- weather_code: 121
  name: 晴朝の内一時雨
- weather_code: 122
  name: 晴夕方一時雨
- weather_code: 123
  name: 晴山沿い雷雨
- weather_code: 124
  name: 晴山沿い雪
- weather_code: 125
  name: 晴午後は雷雨
- weather_code: 126
  name: 晴昼頃から雨
- weather_code: 127
  name: 晴夕方から雨
- weather_code: 128
  name: 晴夜は雨
- weather_code: 130
  name: 朝の内霧後晴
- weather_code: 131
  name: 晴明け方霧
- weather_code: 132
  name: 晴朝夕曇
- weather_code: 140
  name: 晴時々雨で雷を伴う
- weather_code: 160
  name: 晴一時雪か雨
- weather_code: 170
  name: 晴時々雪か雨
- weather_code: 181
  name: 晴後雪か雨
- weather_code: 200
  name: 曇
- weather_code: 201
  name: 曇時々晴
- weather_code: 202
  name: 曇一時雨
- weather_code: 203
  name: 曇時々雨
- weather_code: 204
  name: 曇一時雪
- weather_code: 205
  name: 曇時々雪
- weather_code: 206
  name: 曇一時雨か雪
- weather_code: 207
  name: 曇時々雨か雪
- weather_code: 208
  name: 曇一時雨か雷雨
- weather_code: 209
  name: 霧
- weather_code: 210
  name: 曇後時々晴
- weather_code: 211
  name: 曇後晴
- weather_code: 212
  name: 曇後一時雨
- weather_code: 213
  name: 曇後時々雨
- weather_code: 214
  name: 曇後雨
- weather_code: 215
  name: 曇後一時雪
- weather_code: 216
  name: 曇後時々雪
- weather_code: 217
  name: 曇後雪
- weather_code: 218
  name: 曇後雨か雪
- weather_code: 219
  name: 曇後雨か雷雨
- weather_code: 220
  name: 曇朝夕一時雨
- weather_code: 221
  name: 曇朝の内一時雨
- weather_code: 222
  name: 曇夕方一時雨
- weather_code: 223
  name: 曇日中時々晴
- weather_code: 224
  name: 曇昼頃から雨
- weather_code: 225
  name: 曇夕方から雨
- weather_code: 226
  name: 曇夜は雨
- weather_code: 228
  name: 曇昼頃から雪
- weather_code: 229
  name: 曇夕方から雪
- weather_code: 230
  name: 曇夜は雪
- weather_code: 231
  name: 曇海上海岸は霧か霧雨
- weather_code: 240
  name: 曇時々雨で雷を伴う
- weather_code: 250
  name: 曇時々雪で雷を伴う
- weather_code: 260
  name: 曇一時雪か雨
- weather_code: 270
  name: 曇時々雪か雨
- weather_code: 281
  name: 曇後雪か雨
- weather_code: 300
  name: 雨
- weather_code: 301
  name: 雨時々晴
- weather_code: 302
  name: 雨時々止む
- weather_code: 303
  name: 雨時々雪
- weather_code: 304
  name: 雨か雪
- weather_code: 306
  name: 大雨
- weather_code: 308
  name: 雨で暴風を伴う
- weather_code: 309
  name: 雨一時雪
- weather_code: 311
  name: 雨後晴
- weather_code: 313
  name: 雨後曇
- weather_code: 314
  name: 雨後時々雪
- weather_code: 315
  name: 雨後雪
- weather_code: 316
  name: 雨か雪後晴
- weather_code: 317
  name: 雨か雪後曇
- weather_code: 320
  name: 朝の内雨後晴
- weather_code: 321
  name: 朝の内雨後曇
- weather_code: 322
  name: 雨朝晩一時雪
- weather_code: 323
  name: 雨昼頃から晴
- weather_code: 324
  name: 雨夕方から晴
- weather_code: 325
  name: 雨夜は晴
- weather_code: 326
  name: 雨夕方から雪
- weather_code: 327
  name: 雨夜は雪
- weather_code: 328
  name: 雨一時強く降る
- weather_code: 329
  name: 雨一時みぞれ
- weather_code: 340
  name: 雪か雨
- weather_code: 350
  name: 雨で雷を伴う
- weather_code: 361
  name: 雪か雨後晴
- weather_code: 371
  name: 雪か雨後曇
- weather_code: 400
  name: 雪
- weather_code: 401
  name: 雪時々晴
- weather_code: 402
  name: 雪時々止む
- weather_code: 403
  name: 雪時々雨
- weather_code: 405
  name: 大雪
- weather_code: 406
  name: 風雪強い
- weather_code: 407
  name: 暴風雪
- weather_code: 409
  name: 雪一時雨
- weather_code: 411
  name: 雪後晴
- weather_code: 413
  name: 雪後曇
- weather_code: 414
  name: 雪後雨
- weather_code: 420
  name: 朝の内雪後晴
- weather_code: 421
  name: 朝の内雪後曇
- weather_code: 422
  name: 雪昼頃から雨
- weather_code: 423
  name: 雪夕方から雨
- weather_code: 425
  name: 雪一時強く降る
- weather_code: 426
  name: 雪後みぞれ
- weather_code: 427
  name: 雪一時みぞれ
- weather_code: 450
  name: 雪で雷を伴う
