@startuml Database
package Entity <<Rectangle>> {
  package JMA <<Rectangle>> {
    entity WeatherForecast {
      * 予報日: Date
      --
      # エリアコード: String
      エリア名: String
      天気コード: Number
      風: String
      波: String
      降水確率: Map <<ForecastDataPop>>
      気温: Map <<ForecastDataTemp>>
      発表日時: DateTime 
      登録日時: DateTime
    }

    entity ForecastDataWeather <<Map>> {
      日時: DateTime
      天気コード: Number
      風: String
      波: String
    }

    entity ForecastDataPop <<Map>> {
      日時: DateTime
      降水量: Number
    }

    entity ForecastDataTemp <<Map>> {
      日時: DateTime
      最高気温: Number
      最低気温: Number
    }

    WeatherForecast ||--|| ForecastDataWeather
    WeatherForecast ||--|| ForecastDataPop
    WeatherForecast ||--|| ForecastDataTemp

    hide <<Map>> circle
  }

  package YouTube <<Rectangle>> {
    entity LiveChannel {
      * チャンネルID: String
      --
      # エリアコード: String
      チャンネル名: String
      ストリームURL: String
      ステータス: Number
      最終更新日時: DateTime
      登録日時: DateTime
    }

    entity LiveStreamDetect {
      * ID: Number
      - チャンネルID: String
      --
      傘人数: Number
      半袖人数: Number
      長袖人数: Number
      人数: Number
      登録日時: DateTime
    }
  }

}

package DynamoDB <<Rectangle>> {
  entity WeatherForecast {
    * PK: String <<Partition key>> [エリアコード]
    * SK: String <<Sort key>> [予報日#発表日時]
    --
    data: Map [データ]
    createdAt: DateTime [登録日時]
  }

  entity LiveChannel {
    * PK: String <<Partition key>> [チャンネルID]
    * SK: String <<Sort key>> [ステータス]
    --
    areaCode: String [エリアコード]
    name: String [チャンネル名]
    streamUrl: String [ストリームURL]
    processedAt: DateTime [最終更新日時]
    updatedAt: DateTime [更新日時]
  }

  entity LiveStreamDetect {
    * PK: String <<Partition key>> [エリアコード]
    * SK: String <<Sort key>> [登録日時]
    --
    channelId: String [チャンネルID]
    umbrella: Number [傘人数]
    tshirt: Number [半袖人数]
    longSleeve: Number [長袖人数]
    total: Number [人数]
  }

  object WeatherForecastTable {
    <#lightgray,#black>|=PK|=SK|=data|
    <#white>|1300000|2025-05-01#2025-05-01T12:00:00|{}|
    <#white>|1300000|2025-05-01#2025-05-01T13:00:00|{}|
  }

  object LiveChannelTable {
    <#lightgray,#black>|=PK|=SK|=areaCode|=name|=streamUrl|=processedAt|=updatedAt|
    <#white>|1234|1|1300000|テストチャンネル|https://localhost/|2025-05-01T12:00:00|2025-05-01T12:00:00|
  }

  object LiveStreamDetectTable {
    <#lightgray,#black>|=PK|=SK|=channelId|=umbrella|=tshirt|=longSleeve|=total|
    <#white>|1300000|2025-05-01T12:00:00|1234|1|1|1|3|
  }

  WeatherForecast ||--|| WeatherForecastTable
  LiveChannel ||--|| LiveChannelTable
  LiveStreamDetect ||--|| LiveStreamDetectTable

  Entity.JMA.WeatherForecast ||----|| WeatherForecast
}
@enduml
